version: '3.4'

services:
  mongodb:
    image : mongo
    container_name: Pyramidmongodb
    volumes:
      - Pmongovol:/data/db
    networks:
      - my-network
    ports:
      - 27018:27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: Pyramidmongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=Pyramidmongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - my-network
    ports:
      - 8082:8081

  metrics.timerfunction:
    image: ${DOCKER_REGISTRY-}metricstimerfunction
    build:
      context: .
      dockerfile: Metrics.TimerFunction/Dockerfile

volumes:
  Pmongovol:
  
networks:
  my-network:
    external: true  
