# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- develop
- feature/*

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Metrics.IIS/Metrics.IIS.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publishing API App'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Metrics.IIS/Metrics.IIS.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory) --runtime win-x64 --self-contained true'

- task: PublishPipelineArtifact@1
  displayName: 'Publishing API'
  inputs:
    targetPath: '$(Pipeline.Workspace)/a/Metrics.IIS.zip'
    artifact: 'API'
    publishLocation: 'pipeline'     