name: $(BuildDefinitionName)-$(SourceBranchName)-$(date:yyyyMMdd)$(Rev:.r)

trigger:
- main
- develop
- feature/*

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'Publishing IIS App'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Metrics.IIS/Metrics.IIS.csproj'
    arguments: '--configuration Debug --output $(Build.ArtifactStagingDirectory) --runtime win-x64 --self-contained false'

- task: PublishPipelineArtifact@1
  displayName: 'Publishing IIS'
  inputs:
    targetPath: '$(Pipeline.Workspace)/a/Metrics.IIS.zip'
    artifact: 'IIS'
    publishLocation: 'pipeline'     