# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Function - Dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.x' # set this to the dotnet version to use

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: funkysi1701/metrics-pulumi/dev
          upsert: true
          comment-on-pr: true
          work-dir: Metrics.Pulumi
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  build-and-deploy:
    needs: update
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build Metrics.TimerFunction/Metrics.TimerFunction.csproj --configuration Release --output ./output
          popd

      - name: 'Deploy Azure Functions Action'
        if: github.ref == 'refs/heads/develop'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'metrics-pulumi-timerfunction-dev'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_47691130B9854FEF8F04A8977DE0EE70 }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build Metrics.Function/Metrics.Function.csproj --configuration Release --output ./output
          popd

      - name: 'Deploy Azure Functions Action'
        if: github.ref == 'refs/heads/develop'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'metrics-pulumi-function-dev'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_47691130B9854FEF8F04A8977DE0EE70 }}          

      - name: Application Insights Annotations
        if: github.ref == 'refs/heads/develop'
        uses: wictorwilen/application-insights-action@v1
        with:
          applicationId: ${{ secrets.APPLICATION_ID }}
          apiKey: ${{secrets.API_KEY}}
          releaseName: ${{ github.event_name }}
          message: ${{ github.event.head_commit.message }}
          actor: ${{ github.actor }}