# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Function - Dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.x' # set this to the dotnet version to use

jobs:
  update:
    name: Update
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet publish Metrics.TimerFunction/Metrics.TimerFunction.csproj --configuration Release
          popd
          
      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet publish Metrics.Function/Metrics.Function.csproj --configuration Release
          popd
          
      - uses: pulumi/actions@v3
        id: pulumi-up
        with:
          command: up
          stack-name: funkysi1701/metrics-pulumi/dev
          upsert: true
          comment-on-pr: true
          work-dir: Metrics.Pulumi
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          
      - name: Application Insights Annotations
        if: github.ref == 'refs/heads/develop'
        uses: wictorwilen/application-insights-action@v1
        with:
          applicationId: ${{ steps.pulumi-up.outputs.writeAnnotationsApplicationKey }}
          apiKey: ${{steps.pulumi-up.outputs.writeAnnotationsApiKey}}
          releaseName: ${{ github.event_name }}
          message: ${{ github.event.head_commit.message }}
          actor: ${{ github.actor }}
