# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Destroy - Test

on:
  workflow_dispatch:
  schedule:
    - cron: '21,41 0 1 * *'
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.x' # set this to the dotnet version to use

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x
      - uses: pulumi/actions@v5
        with:
          command: destroy
          stack-name: funkysi1701/metrics-pulumi/test
          upsert: true
          comment-on-pr: true
          work-dir: Metrics.Pulumi
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
